[build]
  Functions = "functions"
  command = "yarn run build"
  publish = "dist"
  NODE_ENV = "12.14.0"

[[redirects]]
 from = "/small/*"
 to = "/.netlify/functions/get-avatar?size=small&user=:splat"
 status = 200

[[redirects]]
 from = "/mid/*"
 to = "/.netlify/functions/get-avatar?size=medium&user=:splat"
 status = 200

[[redirects]]
 from = "/large/*"
 to = "/.netlify/functions/get-avatar?size=large&user=:splat"
 status = 200
